import { MACHINES, GROUPS, GROUP_ICONS } from './machines.js';
import { loadState, saveState, exportState, importState, resetAll, todayKey } from './storage.js';
import { $, $$, esc, fmtDate, fmtDateLong, uid, volume, oneRM, toast, downloadText, confirmModal } from './utils.js';
import { startTimer, stopTimer, initTimer } from './timer.js';

let state = loadState();
let route = 'home';
let groupFilter = '';
let cardioType = 'marche';
let chart = null;

const titles = {home:'Accueil', session:'Séance', history:'Historique', stats:'Stats', settings:'Réglages'};
const view = $('#view');

function persist(){ saveState(state); }
function setTheme(theme){ state.settings.theme = theme; document.documentElement.classList.toggle('light', theme === 'light'); $('#theme-toggle').textContent = theme === 'light' ? '☀️' : '🌙'; persist(); }
function setRoute(next){ route=next; $$('.nav-btn').forEach(b=>b.classList.toggle('is-active', b.dataset.route===route)); $('#page-title').textContent=titles[route]||'GymLog'; render(); }
function filteredMachines(){ return groupFilter ? MACHINES.filter(m=>m.groupe===groupFilter) : MACHINES; }
function machineByName(name){ return MACHINES.find(m=>m.nom===name); }
function lastEntryFor(name){ const all=[]; Object.values(state.history).forEach(day=>all.push(...(day.entries||[]))); all.push(...state.session.entries); return all.reverse().find(e=>e.nom===name); }
function updateRecords(entry){ const prev=Number(state.records[entry.nom]||0); if(Number(entry.poids)>prev) state.records[entry.nom]=Number(entry.poids); }
function defaultMachine(){ return filteredMachines()[0] || MACHINES[0]; }

function home(){ const days=Object.entries(state.history).sort(([a],[b])=>b.localeCompare(a)); const entries=days.flatMap(([d,v])=>(v.entries||[]).map(e=>({...e,date:d}))); const cardio=days.flatMap(([d,v])=>(v.cardio||[]).map(c=>({...c,date:d}))); const totalVol=entries.reduce((s,e)=>s+volume(e),0); const month=new Date().toISOString().slice(0,7); const monthCount=days.filter(([d])=>d.startsWith(month)).length; const bestRM=Math.max(0,...entries.map(e=>Number(e.rm1reel)||oneRM(e.poids,e.reps))); const last=days[0];
return `<div class="grid">
  <div class="card"><div class="eyebrow">Bonjour ${esc(state.settings.userName||'')}</div><h2 style="margin:.3rem 0 0;font-family:Syne">Prêt pour la prochaine séance ?</h2></div>
  <div class="grid-2"><div class="kpi"><strong>${days.length}</strong><span>Séances</span></div><div class="kpi"><strong>${Math.round(totalVol)}</strong><span>Volume total</span></div><div class="kpi"><strong>${monthCount}</strong><span>Ce mois-ci</span></div><div class="kpi"><strong>${bestRM||'—'}</strong><span>Meilleur 1RM</span></div></div>
  <button class="btn primary full" data-route="session">🏋️ Commencer / continuer</button>
  <section><div class="section-title"><h2>Dernière séance</h2></div>${last ? dayCard(last[0], last[1], false) : `<div class="empty">Aucune séance enregistrée.</div>`}</section>
  <section><div class="section-title"><h2>Templates</h2><button class="btn small" data-action="template-new">+ Créer</button></div>${templateList()}</section>
</div>`; }

function templateList(){ if(!state.templates.length) return `<div class="empty">Aucun template. Crée un Push / Pull / Legs par exemple.</div>`; return `<div class="list">${state.templates.map(t=>`<div class="item between"><div><div class="item-title">${esc(t.name)}</div><div class="meta">${t.exercises.length} exercice(s)</div></div><div class="row"><button class="btn small primary" data-action="template-load" data-id="${t.id}">▶</button><button class="btn small danger" data-action="template-delete" data-id="${t.id}">✕</button></div></div>`).join('')}</div>`; }

function sessionView(){ return `<div class="tabs"><button class="tab ${!cardioType?'is-active':''}" data-action="session-tab" data-tab="muscu">Muscu</button><button class="tab ${cardioType?'is-active':''}" data-action="session-tab" data-tab="cardio">Cardio</button></div>${cardioType ? cardioForm() : muscuView()}`; }
function muscuView(){ const m=defaultMachine(); return `<div class="desktop-2"><section class="card"><div class="field"><label>Groupe musculaire</label><div class="chips"><button class="chip ${groupFilter===''?'is-active':''}" data-group="">Tout</button>${GROUPS.map(g=>`<button class="chip ${groupFilter===g?'is-active':''}" data-group="${esc(g)}">${GROUP_ICONS[g]} ${esc(g)}</button>`).join('')}</div></div><div class="field"><label>Exercice</label><select id="machine-select">${filteredMachines().map(x=>`<option value="${esc(x.nom)}">${x.icon} ${esc(x.nom)}</option>`).join('')}</select></div><div id="machine-hint" class="meta"></div><div class="grid-2"><div class="field"><label>Poids</label>${stepper('poids', m?.poids?.[0] || 20, 0.5)}</div><div class="field"><label>Séries</label>${stepper('series',3,1)}</div></div><div class="grid-2"><div class="field"><label>Reps</label>${stepper('reps',10,1)}</div><div class="field"><label>1RM réel optionnel</label><input id="real-rm" type="number" min="0" placeholder="ex: 120"></div></div><button class="btn primary full" data-action="entry-add">+ Ajouter</button></section><section><div class="section-title"><h2>Séance en cours</h2><button class="btn small danger" data-action="session-clear">Effacer</button></div>${currentSessionList()}<button class="btn primary full" style="margin-top:12px" data-action="session-save">💾 Sauvegarder la séance</button></section></div>`; }
function stepper(id, value, step){ return `<div class="stepper"><button data-step-target="${id}" data-step="-${step}">−</button><input id="${id}" type="number" value="${value}" step="${step}" min="0"><button data-step-target="${id}" data-step="${step}">+</button></div>`; }
function currentSessionList(){ const e=state.session.entries, c=state.session.cardio; if(!e.length && !c.length) return `<div class="empty">Aucun exercice. Lance-toi.</div>`; return `<div class="list">${e.map(entryCard).join('')}${c.map(cardioItem).join('')}</div><div class="card" style="margin-top:10px"><div class="between"><span class="muted">Volume séance</span><strong>${Math.round(e.reduce((s,x)=>s+volume(x),0))} kg</strong></div></div>`; }
function entryCard(e){ const rm=Number(e.rm1reel)||oneRM(e.poids,e.reps); return `<div class="item"><div class="between"><div><div class="item-title">${e.icon||''} ${esc(e.nom)}</div><div class="meta">${esc(e.groupe||'')} · ${e.series}×${e.reps} · ${e.poids} kg</div></div><span class="badge blue">1RM ${rm}</span></div><div class="entry-actions"><button class="btn small" data-action="entry-repeat" data-id="${e.id}">Répéter</button><button class="btn small ok" data-action="timer-start" data-name="${esc(e.nom)}">Repos</button><button class="btn small danger" data-action="entry-delete" data-id="${e.id}">Suppr.</button></div></div>`; }
function cardioForm(){ return `<section class="card"><div class="field"><label>Type cardio</label><div class="chips">${['marche','course','velo','escalier'].map(t=>`<button class="chip ${cardioType===t?'is-active':''}" data-cardio-type="${t}">${cardioIcon(t)} ${t}</button>`).join('')}</div></div><div class="grid-3"><div class="field"><label>Durée</label>${stepper('c-duration',20,5)}</div><div class="field"><label>${cardioType==='velo'?'Résistance':cardioType==='escalier'?'Étages':'Vitesse'}</label>${stepper('c-main', cardioType==='velo'?5:cardioType==='escalier'?20:6, cardioType==='velo'||cardioType==='escalier'?1:0.5)}</div><div class="field"><label>${cardioType==='velo'?'RPM':cardioType==='escalier'?'Intensité':'Pente %'}</label>${stepper('c-extra', cardioType==='velo'?80:0, cardioType==='velo'?5:1)}</div></div><button class="btn primary full" data-action="cardio-add">✓ Ajouter cardio</button></section><section><div class="section-title"><h2>Cardio en cours</h2></div>${currentSessionList()}</section>`; }
function cardioIcon(t){ return {marche:'🚶',course:'🏃',velo:'🚴',escalier:'🧗'}[t]||'❤️'; }
function cardioItem(c){ return `<div class="item between"><div><div class="item-title">${cardioIcon(c.type)} ${esc(c.type)}</div><div class="meta">${c.duration} min · ${esc(c.label||'')}</div></div><button class="btn small danger" data-action="cardio-delete" data-id="${c.id}">✕</button></div>`; }
function historyView(){ const days=Object.entries(state.history).sort(([a],[b])=>b.localeCompare(a)); return days.length ? `<div class="list">${days.map(([d,v])=>dayCard(d,v,true)).join('')}</div>` : `<div class="empty">Pas encore d’historique.</div>`; }
function dayCard(date, day, deletable){ const entries=day.entries||[], cardio=day.cardio||[]; const vol=entries.reduce((s,e)=>s+volume(e),0); return `<article class="item"><div class="between"><div><div class="item-title">${fmtDateLong(date)}</div><div class="meta">${entries.length} exercice(s) · ${cardio.length} cardio · ${Math.round(vol)} kg</div></div>${deletable?`<button class="btn small danger" data-action="day-delete" data-date="${date}">Suppr.</button>`:''}</div><div class="list" style="margin-top:10px">${entries.slice(0,8).map(e=>`<div class="between"><span class="small-text">${e.icon||''} ${esc(e.nom)}</span><span class="badge ac">${e.series}×${e.reps} · ${e.poids}kg</span></div>`).join('')}${cardio.map(c=>`<div class="between"><span class="small-text">${cardioIcon(c.type)} ${esc(c.type)}</span><span class="badge purple">${c.duration}min</span></div>`).join('')}</div></article>`; }
function statsView(){ const days=Object.entries(state.history).sort(([a],[b])=>a.localeCompare(b)); const entries=days.flatMap(([d,v])=>(v.entries||[]).map(e=>({...e,date:d}))); const byGroup={}; entries.forEach(e=>byGroup[e.groupe]=(byGroup[e.groupe]||0)+volume(e)); const best=[...entries].sort((a,b)=>(Number(b.rm1reel)||oneRM(b.poids,b.reps))-(Number(a.rm1reel)||oneRM(a.poids,a.reps))).slice(0,5); setTimeout(renderChart,0); return `<div class="grid"><div class="grid-3"><div class="kpi"><strong>${days.length}</strong><span>Séances</span></div><div class="kpi"><strong>${entries.length}</strong><span>Exos</span></div><div class="kpi"><strong>${Math.round(entries.reduce((s,e)=>s+volume(e),0))}</strong><span>Volume</span></div></div><section class="card"><div class="section-title" style="margin-top:0"><h2>Volume par séance</h2></div><div class="chart-box"><canvas id="main-chart"></canvas></div></section><section><div class="section-title"><h2>Volume par groupe</h2></div><div class="list">${Object.entries(byGroup).sort((a,b)=>b[1]-a[1]).map(([g,v])=>`<div class="item between"><span>${GROUP_ICONS[g]||'📌'} ${esc(g)}</span><strong>${Math.round(v)} kg</strong></div>`).join('') || '<div class="empty">Pas assez de données.</div>'}</div></section><section><div class="section-title"><h2>Top 1RM</h2></div><div class="list">${best.map(e=>`<div class="item between"><span>${e.icon||''} ${esc(e.nom)}</span><span class="badge blue">${Number(e.rm1reel)||oneRM(e.poids,e.reps)} kg</span></div>`).join('') || '<div class="empty">Pas encore de record.</div>'}</div></section></div>`; }
function renderChart(){ const canvas=$('#main-chart'); if(!canvas || !window.Chart) return; if(chart) chart.destroy(); const days=Object.entries(state.history).sort(([a],[b])=>a.localeCompare(b)).slice(-12); chart=new Chart(canvas,{type:'line',data:{labels:days.map(([d])=>fmtDate(d)),datasets:[{label:'Volume',data:days.map(([,v])=>(v.entries||[]).reduce((s,e)=>s+volume(e),0)),tension:.35}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{x:{ticks:{color:getComputedStyle(document.documentElement).getPropertyValue('--muted')}},y:{ticks:{color:getComputedStyle(document.documentElement).getPropertyValue('--muted')}}}}}); }
function settingsView(){ return `<div class="grid"><section class="card"><div class="section-title" style="margin-top:0"><h2>Profil</h2></div><div class="field"><label>Prénom</label><input id="setting-name" value="${esc(state.settings.userName||'')}"></div><div class="field"><label>Timer par défaut</label><input id="setting-timer" type="number" value="${state.settings.timerDefault||60}" min="10" step="5"></div><button class="btn primary full" data-action="settings-save">Sauvegarder</button></section><section class="card"><div class="section-title" style="margin-top:0"><h2>Données</h2></div><div class="grid"><button class="btn full" data-action="export-json">Exporter JSON</button><label class="btn full" style="text-align:center">Importer JSON<input id="import-json" type="file" accept="application/json" hidden></label><button class="btn danger full" data-action="reset-all">Réinitialiser toute l’app</button></div></section><section class="card danger-zone"><h2 style="font-family:Syne;margin-top:0">Structure technique</h2><p class="muted small-text">Cette version utilise une seule clé localStorage : <b>gl_app_v3</b>. Les anciennes données sont migrées automatiquement au premier lancement.</p></section></div>`; }

function render(){ $('#today-label').textContent = new Date().toLocaleDateString('fr-FR',{weekday:'long',day:'numeric',month:'long'}); $('#page-title').textContent=titles[route]||'GymLog'; view.innerHTML = ({home,session:sessionView,history:historyView,stats:statsView,settings:settingsView}[route]||home)(); afterRender(); }
function afterRender(){ const select=$('#machine-select'); if(select){ select.addEventListener('change', updateMachineHint); updateMachineHint(); } }
function updateMachineHint(){ const m=machineByName($('#machine-select')?.value); const last=m?lastEntryFor(m.nom):null; const video=m?.video ? ` · <a class="video-link" target="_blank" href="${m.video.startsWith('http')?m.video:'https://youtube.com/watch?v='+m.video}">vidéo</a>` : ''; $('#machine-hint').innerHTML = m ? `Poids disponibles : ${m.poids?.length||0}${last?` · dernier : ${last.poids}kg × ${last.reps}`:''}${video}` : ''; const p=$('#poids'); if(m?.poids?.length && p && !p.dataset.touched) p.value=last?.poids || m.poids[0]; }

function addEntry(){ const m=machineByName($('#machine-select')?.value); if(!m) return toast('Choisis un exercice','warn'); const entry={id:uid(),nom:m.nom,groupe:m.groupe,icon:m.icon,poids:Number($('#poids').value)||0,series:Number($('#series').value)||1,reps:Number($('#reps').value)||1,rm1reel:$('#real-rm').value?Number($('#real-rm').value):null,createdAt:new Date().toISOString()}; entry.rm1est=oneRM(entry.poids,entry.reps); state.session.entries.unshift(entry); updateRecords(entry); persist(); toast('Exercice ajouté','ok'); render(); }
function addCardio(){ const duration=Number($('#c-duration')?.value)||0; const main=Number($('#c-main')?.value)||0; const extra=Number($('#c-extra')?.value)||0; const label = cardioType==='velo' ? `rés. ${main} · ${extra} rpm` : cardioType==='escalier' ? `${main} étages` : `${main} km/h · pente ${extra}%`; state.session.cardio.unshift({id:uid(),type:cardioType,duration,main,extra,label,createdAt:new Date().toISOString()}); persist(); toast('Cardio ajouté','ok'); render(); }
async function saveSession(){ if(!state.session.entries.length && !state.session.cardio.length) return toast('Séance vide','warn'); const day=todayKey(); const prev=state.history[day] || {entries:[],cardio:[]}; state.history[day]={entries:[...state.session.entries,...(prev.entries||[])], cardio:[...state.session.cardio,...(prev.cardio||[])]}; state.session={entries:[],cardio:[]}; persist(); toast('Séance sauvegardée','ok'); setRoute('history'); }
function createTemplateModal(){ const options=MACHINES.map(m=>`<option value="${esc(m.nom)}">${m.icon} ${esc(m.nom)}</option>`).join(''); const root=$('#modal-root'); root.innerHTML=`<div class="modal-backdrop"><div class="modal"><h2>Nouveau template</h2><div class="field"><label>Nom</label><input id="tpl-name" placeholder="Push day"></div><div class="field"><label>Exercices</label><select id="tpl-exos" multiple size="8">${options}</select></div><p class="muted small-text">Astuce : maintiens Ctrl pour en choisir plusieurs sur ordinateur.</p><div class="modal-actions"><button class="btn secondary" data-action="modal-close">Annuler</button><button class="btn primary" data-action="template-save">Créer</button></div></div></div>`; }
function saveTemplate(){ const name=$('#tpl-name')?.value.trim(); const selected=$$('#tpl-exos option:checked').map(o=>o.value); if(!name || !selected.length) return toast('Nom + exercices obligatoires','warn'); state.templates.push({id:uid(),name,exercises:selected.map(n=>({nom:n,series:3,reps:10,poids:lastEntryFor(n)?.poids || machineByName(n)?.poids?.[0] || 20}))}); persist(); $('#modal-root').innerHTML=''; toast('Template créé','ok'); render(); }
async function loadTemplate(id){ const t=state.templates.find(x=>x.id===id); if(!t) return; if(state.session.entries.length && !await confirmModal('La séance en cours sera remplacée.')) return; state.session.entries=t.exercises.map(e=>{ const m=machineByName(e.nom); return {id:uid(),nom:e.nom,groupe:m?.groupe,icon:m?.icon,poids:e.poids,series:e.series,reps:e.reps,rm1est:oneRM(e.poids,e.reps),rm1reel:null,createdAt:new Date().toISOString()}; }); state.session.cardio=[]; persist(); toast('Template chargé','ok'); setRoute('session'); }

function bindEvents(){ document.addEventListener('click', async e=>{ const routeBtn=e.target.closest('[data-route]'); if(routeBtn) return setRoute(routeBtn.dataset.route); const group=e.target.closest('[data-group]'); if(group){ groupFilter=group.dataset.group; cardioType=''; return render(); } const ctype=e.target.closest('[data-cardio-type]'); if(ctype){ cardioType=ctype.dataset.cardioType; return render(); } const step=e.target.closest('[data-step-target]'); if(step){ const input=$('#'+step.dataset.stepTarget); input.dataset.touched='1'; input.value=String(Math.max(Number(input.min||0), (Number(input.value)||0)+Number(step.dataset.step))); return; } const action=e.target.closest('[data-action]')?.dataset.action; if(!action) return; const el=e.target.closest('[data-action]'); if(action==='session-tab'){ cardioType = el.dataset.tab==='cardio' ? 'marche' : ''; render(); }
  if(action==='entry-add') addEntry();
  if(action==='cardio-add') addCardio();
  if(action==='entry-delete'){ state.session.entries=state.session.entries.filter(x=>x.id!==el.dataset.id); persist(); render(); }
  if(action==='cardio-delete'){ state.session.cardio=state.session.cardio.filter(x=>x.id!==el.dataset.id); persist(); render(); }
  if(action==='entry-repeat'){ const old=state.session.entries.find(x=>x.id===el.dataset.id); if(old){ state.session.entries.unshift({...old,id:uid(),createdAt:new Date().toISOString()}); persist(); render(); } }
  if(action==='timer-start') startTimer(state.settings.timerDefault||60, el.dataset.name||'Repos');
  if(action==='session-save') saveSession();
  if(action==='session-clear' && await confirmModal('Effacer la séance en cours ?')){ state.session={entries:[],cardio:[]}; persist(); render(); }
  if(action==='day-delete' && await confirmModal('Supprimer cette journée ?')){ delete state.history[el.dataset.date]; persist(); render(); }
  if(action==='template-new') createTemplateModal();
  if(action==='template-save') saveTemplate();
  if(action==='template-load') loadTemplate(el.dataset.id);
  if(action==='template-delete' && await confirmModal('Supprimer ce template ?')){ state.templates=state.templates.filter(t=>t.id!==el.dataset.id); persist(); render(); }
  if(action==='modal-close') $('#modal-root').innerHTML='';
  if(action==='settings-save'){ state.settings.userName=$('#setting-name').value.trim()||'Kevin'; state.settings.timerDefault=Number($('#setting-timer').value)||60; persist(); toast('Réglages sauvegardés','ok'); render(); }
  if(action==='export-json') downloadText(`gymlog-backup-${todayKey()}.json`, exportState(state));
  if(action==='reset-all' && await confirmModal('Tout supprimer définitivement ?')){ resetAll(); state=loadState(); setTheme('dark'); setRoute('home'); toast('Application réinitialisée','ok'); }
 });
 $('#theme-toggle').addEventListener('click',()=>setTheme(state.settings.theme==='light'?'dark':'light'));
 document.addEventListener('change', async e=>{ if(e.target.id==='import-json'){ const file=e.target.files[0]; if(!file) return; try{ state=importState(await file.text()); setTheme(state.settings.theme); toast('Import réussi','ok'); setRoute('home'); }catch(err){ toast('Import impossible : '+err.message,'warn'); } } });
}

setTheme(state.settings.theme || 'dark');
initTimer(()=>state.settings.timerDefault||60);
bindEvents();
render();
